apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  destination:
    namespace: applications
    server: https://kubernetes.default.svc
  project: my-project
  source:
    path: apps
    repoURL: https://github.com/matiasmagallanes/root-apps
    targetRevision: HEAD
    
